# --- _config.yml ---
remote_theme: clayh53/tufte-jekyll      # pull the Tufte-CSS Jekyll theme
plugins:
  - jekyll-remote-theme                # REQUIRED for `remote_theme`

url: "https://dominiccoey.github.io"    # your GitHub Pages root
baseurl: "/essays"                      # repo name preceded by a slash

title: ""                               # empty => no big banner
description: "Essays with Tufte-CSS + KaTeX"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex                    # kramdown parses \( \) & $$ $$

highlighter: rouge
