# --- _config.yml ---
remote_theme: clayh53/tufte-jekyll
plugins:
  - jekyll-remote-theme    # so remote_theme: is honored

url: "https://dominiccoey.github.io"
baseurl: "/essays"         # your repo’s name

title: ""                  # no big banner
description: "Tufte-Jekyll + MathJax demo"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax     # leave your \(…\) & $$…$$ in place

highlighter: rouge
