# ---  _config.yml  ---
title: "Essay"
description: "A minimalist Tufte-style page with KaTeX math"
remote_theme: ab/ab/jekyll-theme-tufte@c3c83e3      # pulls the Tufte theme at build time
plugins: [jekyll-remote-theme]           # lets GitHub use the remote theme

markdown: kramdown                       # GitHub’s default Markdown engine
kramdown:
  input: GFM                             # GitHub-Flavored Markdown
  math_engine: katex                     # change to 'mathjax' if you prefer

highlighter: rouge                       # syntax highlight for code blocks
