# --- _config.yml ---
theme: minima
minima:
  skin: solarized    Light variant of solarized color scheme.

url: "https://dominiccoey.github.io"
baseurl: "/essays"         # your repo’s name

title: ""                  # no big banner
description: "Tufte-Jekyll + MathJax, demo"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax     # leave your \(…\) & $$…$$ in place

highlighter: rouge

header_pages: []
