# --- _config.yml ---
remote_theme: jekyll/minima@master
plugins:
  - jekyll-remote-theme

minima:
  skin: solarized-light    Light variant of solarized color scheme.

url: "https://dominiccoey.github.io"
baseurl: "/essays"         # your repo’s name

title: ""                  # no big banner
description: "Tufte-Jekyll + MathJax, demo"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax     # leave your \(…\) & $$…$$ in place

highlighter: rouge
