# --- _config.yml ---
remote_theme: clayh53/tufte-jekyll
plugins:
  - jekyll-remote-theme

url: "https://dominiccoey.github.io"
baseurl: "/essays"            # must match your repo name

title: ""                     # omit the banner
description: "Tufte-Jekyll + KaTeX demo"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex          # kramdown only parses the delimiters

highlighter: rouge
