# --- _config.yml ---
remote_theme: clayh53/tufte-jekyll
plugins:
  - jekyll-remote-theme

url: "https://dominiccoey.github.io"
baseurl: "/essays"

title: ""                                # suppress the banner
description: "Tufte-Jekyll with MathJax"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax                   # kramdown will leave your \(…\) & $$…$$ intact

highlighter: rouge
