# --- _config.yml ---
remote_theme: clayh53/tufte-jekyll
plugins:
  - jekyll-remote-theme

url: "https://dominiccoey.github.io"
baseurl: "/essays"

title: ""                                # hides the big banner
description: "Tufte-Jekyll + KaTeX demo"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex

highlighter: rouge
